import json

import sympy as sp

_I = sp.I
_LAMBDA = sp.Symbol('lambda', positive=True)
_M = sp.Symbol('m', positive=True)
_E = sp.Symbol('e', positive=True)


# ── Scalar theories (φ⁴, φ³) ─────────────────────────────────────────────────

def simplify_amplitude(vertex_count, propagators, symmetry_factor):
    """
    Builds the φ⁴/φ³ combined amplitude — (−iλ)^V times one i/(q²−m²)
    propagator per internal line, divided by the symmetry factor — and
    returns its LaTeX.

    propagators: list of {"terms": [{"sign": 1, "symbol": "p_{1}"}, ...]},
                 one per internal edge, mirroring momentum.js's MomentumExpr.

    Only the momentum-free scalar part is run through sp.simplify(). The
    propagator denominators are assembled as plain LaTeX text to avoid SymPy
    re-ordering or factoring them in unreadable ways.
    """
    vertex_term = (-_I * _LAMBDA) ** vertex_count
    scalar = sp.simplify(vertex_term * _I ** len(propagators) / symmetry_factor)
    scalar_numerator, scalar_denominator = sp.fraction(scalar)

    numerator_latex = sp.latex(scalar_numerator)
    denominator_latex = '' if scalar_denominator == 1 else sp.latex(scalar_denominator)
    denominator_latex += ''.join(
        rf'\left({_fermion_denominator_latex(p)}\right)' for p in propagators
    )

    if not denominator_latex:
        return numerator_latex
    return rf'\frac{{{numerator_latex}}}{{{denominator_latex}}}'


# ── QED ──────────────────────────────────────────────────────────────────────

def simplify_qed_amplitude(vertex_count, fermion_propagators, photon_propagators,
                            symmetry_factor):
    """
    Builds the QED amplitude scalar prefactor and propagator denominators.

    Scalar prefactor: (−ie)^V · i^{I_f} · (−i)^{I_γ} / S
      — this collects all factors of i and e that SymPy can simplify.

    Propagator denominators:
      fermion line: q² − m²
      photon line:  k²  (massless)

    Spinor/polarisation factors (ū, u, ε, ε*, γ^μ matrices) and Dirac traces
    require diagram-topology information not yet tracked in the graph model,
    so they are annotated symbolically rather than evaluated.
    """
    I_f     = len(fermion_propagators)
    I_gamma = len(photon_propagators)

    scalar = sp.simplify(
        (-_I * _E) ** vertex_count * _I ** I_f * (-_I) ** I_gamma / symmetry_factor
    )
    scalar_num, scalar_den = sp.fraction(scalar)

    num_latex  = sp.latex(scalar_num)
    den_parts  = [] if scalar_den == 1 else [sp.latex(scalar_den)]

    for p in fermion_propagators:
        den_parts.append(rf'\left({_fermion_denominator_latex(p)}\right)')
    for p in photon_propagators:
        den_parts.append(rf'\left({_photon_denominator_latex(p)}\right)')

    den_latex = ''.join(den_parts)
    if den_latex:
        expr = rf'\frac{{{num_latex}}}{{{den_latex}}}'
    else:
        expr = num_latex

    note = r'\;\bigl[\bar{u},\,u,\,\varepsilon,\,\gamma^\mu\ \text{not evaluated}\bigr]'
    return expr + note


# ── JSON entry point ──────────────────────────────────────────────────────────

def simplify_amplitude_json(payload_json):
    """JSON-string entry point for src/sympy-bridge.js.

    Dispatches to the appropriate simplification function based on the
    'theory' field in the payload ('scalar' or 'qed'; defaults to 'scalar'
    for payloads generated by older versions of the bridge).
    """
    payload = json.loads(payload_json)
    theory  = payload.get('theory', 'scalar')

    if theory == 'qed':
        return simplify_qed_amplitude(
            payload['vertexCount'],
            payload['fermionPropagators'],
            payload['photonPropagators'],
            payload['symmetryFactor'],
        )
    return simplify_amplitude(
        payload['vertexCount'],
        payload['propagators'],
        payload['symmetryFactor'],
    )


# ── Helpers ───────────────────────────────────────────────────────────────────

def _momentum_symbol(prop):
    """Builds a SymPy expression for a MomentumExpr dict."""
    q = sp.Integer(0)
    for term in prop['terms']:
        q += term['sign'] * sp.Symbol(term['symbol'])
    # q² == (−q)², so prefer the positive-looking form for readability.
    if q.could_extract_minus_sign():
        q = -q
    return q


def _fermion_denominator_latex(prop):
    """q² − m² for a massive fermion propagator."""
    q = _momentum_symbol(prop)
    q_latex = sp.latex(q)
    squared  = q_latex if q.is_Symbol else rf'\left({q_latex}\right)'
    return rf'{squared}^{{2}} - m^{{2}}'


def _photon_denominator_latex(prop):
    """k² for a massless photon propagator."""
    k = _momentum_symbol(prop)
    k_latex = sp.latex(k)
    squared  = k_latex if k.is_Symbol else rf'\left({k_latex}\right)'
    return rf'{squared}^{{2}}'
